function functie_calcul(R, L, f)

figure('Name','Filtru trece jos - RL', ...
    'Units','normalized', ...
    'NumberTitle','off', ...
    'Position',[0.1 0.1 0.8 0.8], ...
    'Color','#F8BFD6');

 r=uimenu('Label','Documentatie Proiect');
   uimenu(r,'Label','Prezentare PowerPoint','Callback','open(''Prezentare.pptx'')');
   uimenu(r,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');


RadioGroup1=uibuttongroup('Visible','on', ...
 'BackgroundColor','#F0D6F6', ...
 'Title','Date de intrare', ...
 'FontSize',10, ...
 'TitlePosition','centertop', ...
 'Tag','radiobutton', ...
 'Position',[0.05 0.5 0.26 0.47]); 

% Rezistența
uicontrol('Style','text', ...
 'Units','normalized', ...
 'Position',[0.09 0.73 0.08 .07], ...
 'string','Rezistența [Ω] = ', ...
 'BackgroundColor','#F0D6F6');  

uicontrol('Style','edit', ...
 'Units','normalized', ...
 'Position',[0.19 0.73 0.1 .07], ...
 'String',R, ...
 'BackgroundColor','#FFF0F6', ...
 'Callback','R=str2num(get(gco,''String''));close;functie_calcul(R,L, f)');

% Inductanța
uicontrol('Style','text', ...
 'Units','normalized', ...
 'Position',[0.09 0.63 0.08 .07], ...
 'string','Inductanța [H] = ', ...
 'BackgroundColor','#F0D6F6'); 

uicontrol('Style','edit', ...
 'Units','normalized', ...
 'Position',[0.19 0.63 0.1 .07], ...
 'String',L, ...
 'BackgroundColor','#FFF0F6', ...
 'Callback','L=str2num(get(gco,''String''));close;functie_calcul(R,L, f)');

% Frecvența
uicontrol('Style','text', ...
 'Units','normalized', ...
 'Position',[0.09 0.53 0.08 .07], ...
 'string','Frecvența [Hz] = ', ...
 'BackgroundColor','#F0D6F6');

uicontrol('Style','edit', ...
 'Units','normalized', ...
 'Position',[0.19 0.53 0.1 .07], ...
 'String',f, ... 
 'BackgroundColor','#FFF0F6', ...
 'Callback','f=str2num(get(gco,''String''));close;functie_calcul(R,L, f)');


ft = R/(2*pi*L); % Frecvența de tăiere
w0 = R/L;       % Pulsația de tăiere
xl = 2*pi*f*L;  % Reactanța inductivă
T = 1/f;        % Perioada
zl = sqrt(R*R + xl*xl); % Impedanța

RadioGroup1=uibuttongroup('Visible','on',...
 'BackgroundColor','#F0D6F6',... 
 'ForegroundColor','black',...
 'Title','Valori obținute',...
 'FontSize',10,...
 'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.43 0.5 0.25 0.47]); 

uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.46 0.77 0.08 .07],...
 'string','Frecvența de tăiere = ',...
 'BackgroundColor','#F0D6F6');

uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.56 0.77 0.1 .07],...
 'String',ft,...
 'BackgroundColor','#FFF0F6',...
 'Callback',['ft=','str2num(get(gco,''String''))']);

uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.46 0.67 0.08 .07],...
 'string','Pulsația = ',...
 'BackgroundColor','#F0D6F6')

uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.56 0.67 0.1 .07],...
 'String',w0,...
 'BackgroundColor','#FFF0F6',... 
 'Callback',['w0=','str2num(get(gco,''String''))']);

uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.46 0.55 0.08 .07],...
 'string',' Perioada = ',...
 'BackgroundColor','#F0D6F6');

uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.56 0.55 0.1 .07],...
  'String',T,...
  'BackgroundColor','#FFF0F6',...
 'Callback',['T=','str2num(get(gco,''String''))']);


RadioGroup1=uibuttongroup('Visible','on',...
 'BackgroundColor','#F0D6F6',...
  'Title','Valori obținute',...
 'FontSize',10,...
 'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.75 0.28 0.26 0.27]); 

uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.8 0.4 0.09 .07],...
 'string',' Reactanța inductivă = ',...
 'BackgroundColor','#F0D6F6');

uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.9 0.4 0.1 .07],...
  'String',xl,...
   'BackgroundColor','#FFF0F6',...
 'Callback',['xl=','str2num(get(gco,''String''))']);

uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.8 0.3 0.09 .07],...
'string',' Impedanța = ',...
 'BackgroundColor','#F0D6F6');

uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.9 0.3 0.1 .07],...
  'String',zl,...
  'BackgroundColor','#FFF0F6',...
 'Callback',['zl=','str2num(get(gco,''String''))']);


% Vector de pulsatii pentru grafic care variaza intre 10^0 si 10^5
w = logspace(0, 5, 500);
num = 1;                 % Numărătorul funcției de transfer
den = 1 + j*(L./R).*w;    % Numitorul funcției de transfer

h = abs(num ./ den);      % Modulul funcției de transfer
gain = 20*log10(h);       % Câștigul în decibeli
f = w / (2*pi);           % Conversie în frecvență
phase = angle(num ./ den) * 180 / pi; % Calculeaza faza în grade

 % Butonul pentru graficul câștigului
    uicontrol('Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.43 0.2 0.05], ...
        'String', 'Graficul câștigului', ...
        'Callback', @showGain);

    % Butonul pentru graficul fazei
    uicontrol('Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.46 0.43 0.2 0.05], ...
        'String', 'Graficul fazei', ...
        'Callback', @showPhase);

    % Funcția pentru a arăta graficul câștigului
    function showGain(~, ~)
        subplot('Position', [0.05 0.09 0.3 0.3]);
        semilogx(f, gain, 'm', 'LineWidth', 2);
        grid on;
        xlabel('Frecvența [Hz]');
        ylabel('Câștig [dB]');
        title('Câștig în funcție de frecvență');
    end

    % Funcția pentru a arăta graficul fazei
    function showPhase(~, ~)
        subplot('Position', [0.4 0.09 0.3 0.3]);
        semilogx(f, phase, 'm', 'LineWidth', 2);
        grid on;
        xlabel('Frecvența [Hz]');
        ylabel('Faza [°]');
        title('Faza în funcție de frecvență');
    end


% Afișarea imaginii
I = imread("rl-low-pass-filter.jpg");
axes('Position', [0.75 0.6 0.25 0.4]); % Poziționare clară pentru imagine
imshow(I);
title('Reprezentare Filtru RL');

% Validare
if R < 1
    error('Valoare greșită a rezistenței');
end

% Buton de închidere
uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.91 0.05 0.07 0.05], ...
    'string','Inapoi', ...
    'Callback','pagina_de_start');

end

