function functie_grafice(A, N, R, L)

figure('Name','Semnal de intrare si iesire',... 
 'Units','normalized',...
 'Position',[0.1 0.09 0.8 0.83],...
 'NumberTitle','off'); 
set(gcf, 'Color','#A8D5BA');  

RadioGroup1=uibuttongroup('Visible','on',...
        'BackgroundColor','#A0C9A9',...  
        'ForegroundColor','white',...
        'Title','Parametrii semnalului',...
        'FontSize',19,...
        'Position', [0.6 0.4 0.25 0.3],...
        'FontWeight','Bold',...
        'Fontname','Aharoni',...
        'TitlePosition','centertop',...
        'Tag','radiobutton'); 

    uicontrol('Style','text',... 
                'Units','normalized',...
                'Position',[0.05 0.67 0.47 0.27],...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'FontSize',16,...
                'FontWeight','bold',...
                'HorizontalAlignment','left',...
                'String','Amplitudinea A[V] = ',...
                'Parent',RadioGroup1);
                
    uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'String',A,...
                'Position',[0.55 0.72 0.4 0.18],...
                'FontSize',16,...
                'FontWeight','bold',...
                'Parent',RadioGroup1,...
                'Callback', 'A=str2num(get(gco,''String'')); close; functie_grafice(A, N, R, L)');

    uicontrol('Style','text',... 
                'Units','normalized',...
                'Position',[0.05 0.3 0.45 0.2],...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'FontSize',16,...
                'FontWeight','bold',...
                'HorizontalAlignment','left',...
                'String', 'N = ',...
                'Parent',RadioGroup1);

    uicontrol('Style','edit',...
                'Units','normalized',...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'String',N,... 
                'Position',[0.55 0.32 0.4 0.18],...
                'FontSize',16,... 
                'FontWeight','bold',...
                'Parent',RadioGroup1,...    
                'Callback','N=str2num(get(gco,''String'')); close; functie_grafice(A, N, R, L)');

% Functia de transfer
f=5000; %Hz, setez fecventa semnalului
T=1/f;
t=0:T/100:N*T;
Vi=A*sin(2*pi*f*t); %semnalul de intrare
w=2*pi*f; %frecventa unghiulara(omega)
Hw = R / (R + 1i * w * L); %functia de transfer

Vo=abs(Hw)*Vi; %abs-modul

subplot ('Position', [0.06 0.6 0.40 0.3]);
plot (t,Vi,'g');  
grid on;
axis on;
title('Tensiunea de intrare[Vi]','FontSize',15,'Fontweight','b');
xlabel('t [ms]');
ylabel('A [V]');

subplot ('Position', [0.06 0.1 0.40 0.3]);
plot (t,Vo,'g'); 
grid on;
axis on;
title('Tensiunea de iesire[Vo]','FontSize',15,'Fontweight','b');
xlabel('t [ms]');
ylabel('A [V]');

uicontrol('style','pushbutton',... 
          'Units','normalized',... 
          'Position',[0.85 0.02 0.1 0.06],... 
          'string','Inapoi',... 
          'FontName','Aharon',... 
          'backgroundcolor','#A0C9A9',...  
          'foregroundcolor','white',... 
          'FontSize',19,...  
          'FontWeight','Bold',... 
          'Callback','pagina_de_start');        

end