Fig=figure('Name','RL-FTJ', 'Units','normalized', 'Position',[0.1 0.1 0.8 0.8],  'NumberTitle','off');
       
x = imread('el2.jpg'); %imread este utilizată pentru a citi fișiere de imagini
image(x);
set(gca,'Position',[0 0 1 1]);
axis off;

uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.3 0.77 0.37 0.11],...
'backgroundcolor','#F2F3F4',...
'Fontname','Calibri',...
'FontSize',24,...
'String','Filtru trece jos - RL');


uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.7 0.05 0.28 0.05],...
'FontSize',16,...
'Backgroundcolor','#f1ebf5',...
'String','Varo Gabriela-Bianca');
      
uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.7 0.01 0.28 0.05],...
'FontSize',16,...
'Backgroundcolor','#f1ebf5',...
'String','grupa 2124');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.04 0.35 0.2 0.11],...
          'string',' Proiect ',...
          'FontName','Calibri',...
          'FontSize',15,...
          'Backgroundcolor','#dce1f5',...
          'Callback','int');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.2 0.1 0.2 0.11],...
          'string',' Grafice ',...
          'FontName','Calibri',...
          'FontSize',15,...
          'Backgroundcolor','#dce1f5',...
          'Callback','grafice');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.4 0.35 0.2 0.11],...
          'string',' Prezentare ',...
          'FontName','Calibri',...
          'FontSize',15,...
          'Backgroundcolor','#dce1f5',...
          'Callback','open (''Prezentare.pptx'')');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.77 0.35 0.2 0.11],...
          'string',' Documentatie ',...
          'FontName','Calibri',...
          'FontSize',15,...
          'Backgroundcolor','#dce1f5',...
          'Callback', 'open(''CircuitRL.docx'')');